version: "8.3"
services:
  shortener-db:
    container_name: shortener-db
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - shortener-db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  shortener-pgadmin:
    image: dpage/pgadmin4
    container_name: shortener-pgadmin
    environment:
      PGADMIN_DEFAULT_USERNAME: postgres
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - shortener-db

  shortener-cache:
    container_name: shortener-cache
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - shortener-cache-data:/data

  shortener-redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - shortener-redis-insight:/data

volumes:
  shortener-db-data:
  shortener-cache-data:
  shortener-redis-insight: